# Generated by Django 2.2.7 on 2019-11-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bulk_edit',
            field=models.BooleanField(
                default=True,
                help_text='If Bulk Edit is set, this user can edit multiple interfaces at once on switches.',
                verbose_name='Bulk-editing of interfaces',
            ),
        ),
    ]
