# Generated by Django 2.2.7 on 2019-11-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_profile_bulk_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_poe_toggle',
            field=models.BooleanField(
                default=False, help_text='If set, allow PoE toggle on all interfaces', verbose_name='Poe Toggle All'
            ),
        ),
    ]
