# Generated by Django 2.2.8 on 2019-12-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_profile_allow_poe_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='edit_if_descr',
            field=models.BooleanField(
                default=True,
                help_text='If set, allow interface descriptions to be edited.',
                verbose_name='Edit Port Description',
            ),
        ),
    ]
