# Generated by Django 2.2.9 on 2020-01-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tasks',
            field=models.BooleanField(default=False, help_text='If Tasks is set, this user can schedule changes on switches at some future date.', verbose_name='Allow scheduled tasks'),
        ),
    ]
