# Generated by Django 3.2.12 on 2022-03-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_ldap_dn',
            field=models.CharField(blank=True, help_text='The LDAP DN of the last LDAP login (if any)', max_length=128, verbose_name='Last LDAP DN'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_ldap_login',
            field=models.DateTimeField(blank=True, help_text='The time of the most recent LDAP login (if any)', null=True, verbose_name='Last LDAP login time'),
        ),
    ]
