# Generated by Django 3.2.12 on 2022-03-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_auto_20220323_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_ldap_login',
            field=models.DateTimeField(
                blank=True,
                help_text='The time of the most recent LDAP login (if any)',
                null=True,
                verbose_name='Last LDAP login',
            ),
        ),
    ]
