# Generated by Django 4.2.2 on 2023-07-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_profile_vlan_edit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_ldap_dn",
            field=models.CharField(
                blank=True,
                help_text="The LDAP DN of the last LDAP login (if any)",
                max_length=1024,
                verbose_name="Last LDAP DN",
            ),
        ),
    ]
