# Generated by Django 5.0.4 on 2024-04-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(
                default='light',
                help_text='Set to a valid theme name',
                max_length=40,
                verbose_name='The Theme selected',
            ),
        ),
    ]
