# Generated by Django 5.2.4 on 2025-08-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='menu',
            field=models.BooleanField(
                default=True,
                help_text='If unchecked, device menu is hidden and only search bar will be displayed',
                verbose_name='Show Menu',
            ),
        ),
    ]
