# Generated by Django 4.2 on 2023-04-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notices", "0002_alter_notice_content_alter_notice_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="priority",
            field=models.PositiveSmallIntegerField(
                choices=[[20, "Information"], [25, "Success"], [30, "Warning"]],
                default=30,
                help_text="Priority of this notice, as defined by Message Levels",
                verbose_name="Notice priority",
            ),
        ),
    ]
