# Generated by Django 5.0.4 on 2024-05-09 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_alter_notice_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
