# Generated by Django 2.2.7 on 2019-11-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0003_auto_20191108_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netmikoprofile',
            name='enable_password',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Netmiko/SSH enable password, e.g. for Cisco devices (optional)'),
        ),
        migrations.AlterField(
            model_name='snmpprofile',
            name='community',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='v2c Community name'),
        ),
    ]
