# Generated by Django 3.2.6 on 2021-08-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0023_auto_20210519_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='details_read_count',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='read_count',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='write_count',
        ),
    ]
