# Generated by Django 3.2.7 on 2021-09-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('switches', '0025_alter_switch_connector_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name as shown to the user', max_length=32)),
                (
                    'os',
                    models.CharField(
                        blank=True, help_text='The switch OS name, for easier displaying & sorting', max_length=32
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True,
                        help_text='Explanation of command template, shown as hover-over to user',
                        max_length=250,
                    ),
                ),
                (
                    'template',
                    models.CharField(
                        help_text='The command template. Use {{field[1-8]}} or {{list[1-3]}} as needed.',
                        max_length=64,
                        verbose_name='Command Template',
                    ),
                ),
                (
                    'field1_name',
                    models.CharField(
                        blank=True, help_text='Command template field 1 name.', max_length=64, verbose_name='Name'
                    ),
                ),
                (
                    'field1_description',
                    models.CharField(
                        blank=True,
                        help_text='Command template field 1 description.',
                        max_length=64,
                        verbose_name='Description',
                    ),
                ),
                (
                    'field1_regex',
                    models.CharField(
                        blank=True,
                        help_text='Command template field 1 validation regular expression.',
                        max_length=100,
                        verbose_name='Regex',
                    ),
                ),
                (
                    'field2_name',
                    models.CharField(
                        blank=True, help_text='Command template field 2 name.', max_length=64, verbose_name='Name'
                    ),
                ),
                (
                    'field2_description',
                    models.CharField(
                        blank=True,
                        help_text='Command template field 2 description.',
                        max_length=64,
                        verbose_name='Description',
                    ),
                ),
                (
                    'field2_regex',
                    models.CharField(
                        blank=True,
                        help_text='Command template field 2 validation regular expression.',
                        max_length=100,
                        verbose_name='Regex',
                    ),
                ),
                (
                    'field3_name',
                    models.CharField(
                        blank=True, help_text='Command template field 3 name.', max_length=64, verbose_name='Name'
                    ),
                ),
                (
                    'field3_description',
                    models.CharField(
                        blank=True,
                        help_text='Command template field 3 description.',
                        max_length=64,
                        verbose_name='Description',
                    ),
                ),
                (
                    'field3_regex',
                    models.CharField(
                        blank=True,
                        help_text='Command template field 3 validation regular expression.',
                        max_length=100,
                        verbose_name='Regex',
                    ),
                ),
                (
                    'field4_name',
                    models.CharField(
                        blank=True, help_text='Command template field 4 name.', max_length=64, verbose_name='Name'
                    ),
                ),
                (
                    'field4_description',
                    models.CharField(
                        blank=True,
                        help_text='Command template field41 description.',
                        max_length=64,
                        verbose_name='Description',
                    ),
                ),
                (
                    'field4_regex',
                    models.CharField(
                        blank=True,
                        help_text='Command template field 4 validation regular expression.',
                        max_length=100,
                        verbose_name='Regex',
                    ),
                ),
                (
                    'field5_name',
                    models.CharField(
                        blank=True, help_text='Command template field 5 name.', max_length=64, verbose_name='Name'
                    ),
                ),
                (
                    'field5_description',
                    models.CharField(
                        blank=True,
                        help_text='Command template field 5 description.',
                        max_length=64,
                        verbose_name='Description',
                    ),
                ),
                (
                    'field5_regex',
                    models.CharField(
                        blank=True,
                        help_text='Command template field 5 validation regular expression.',
                        max_length=100,
                        verbose_name='Regex',
                    ),
                ),
                (
                    'field6_name',
                    models.CharField(
                        blank=True, help_text='Command template field 6 name.', max_length=64, verbose_name='Name'
                    ),
                ),
                (
                    'field6_description',
                    models.CharField(
                        blank=True,
                        help_text='Command template field 6 description.',
                        max_length=64,
                        verbose_name='Description',
                    ),
                ),
                (
                    'field6_regex',
                    models.CharField(
                        blank=True,
                        help_text='Command template field 6 validation regular expression.',
                        max_length=100,
                        verbose_name='Regex',
                    ),
                ),
                (
                    'field7_name',
                    models.CharField(
                        blank=True, help_text='Command template field 7 name.', max_length=64, verbose_name='Name'
                    ),
                ),
                (
                    'field7_description',
                    models.CharField(
                        blank=True,
                        help_text='Command template field 7 description.',
                        max_length=64,
                        verbose_name='Description',
                    ),
                ),
                (
                    'field7_regex',
                    models.CharField(
                        blank=True,
                        help_text='Command template field 7 validation regular expression.',
                        max_length=100,
                        verbose_name='Regex',
                    ),
                ),
                (
                    'field8_name',
                    models.CharField(
                        blank=True, help_text='Command template field 8 name.', max_length=64, verbose_name='Name'
                    ),
                ),
                (
                    'field8_description',
                    models.CharField(
                        blank=True,
                        help_text='Command template field 8 description.',
                        max_length=64,
                        verbose_name='Description',
                    ),
                ),
                (
                    'field8_regex',
                    models.CharField(
                        blank=True,
                        help_text='Command template field 8 validation regular expression.',
                        max_length=100,
                        verbose_name='Regex',
                    ),
                ),
                (
                    'list1_name',
                    models.CharField(
                        blank=True, help_text='Command template pick list 1 name.', max_length=64, verbose_name='Name'
                    ),
                ),
                (
                    'list1_description',
                    models.CharField(
                        blank=True,
                        help_text='Command template pick list 1 description.',
                        max_length=64,
                        verbose_name='Description',
                    ),
                ),
                (
                    'list1_values',
                    models.CharField(
                        blank=True,
                        help_text='Command template pick list 1 comma-separated values.',
                        max_length=100,
                        verbose_name='Values',
                    ),
                ),
                (
                    'list2_name',
                    models.CharField(
                        blank=True, help_text='Command template pick list 2 name.', max_length=64, verbose_name='Name'
                    ),
                ),
                (
                    'list2_description',
                    models.CharField(
                        blank=True,
                        help_text='Command template pick list 2 description.',
                        max_length=64,
                        verbose_name='Description',
                    ),
                ),
                (
                    'list2_values',
                    models.CharField(
                        blank=True,
                        help_text='Command template pick list 2 comma-separated values.',
                        max_length=100,
                        verbose_name='Values',
                    ),
                ),
                (
                    'list3_name',
                    models.CharField(
                        blank=True, help_text='Command template pick list 3 name.', max_length=64, verbose_name='Name'
                    ),
                ),
                (
                    'list3_description',
                    models.CharField(
                        blank=True,
                        help_text='Command template pick list 3 description.',
                        max_length=64,
                        verbose_name='Description',
                    ),
                ),
                (
                    'list3_values',
                    models.CharField(
                        blank=True,
                        help_text='Command template pick list 3 comma-separated values.',
                        max_length=100,
                        verbose_name='Values',
                    ),
                ),
                (
                    'list4_name',
                    models.CharField(
                        blank=True, help_text='Command template pick list 4 name.', max_length=64, verbose_name='Name'
                    ),
                ),
                (
                    'list4_description',
                    models.CharField(
                        blank=True,
                        help_text='Command template pick list 4 description.',
                        max_length=64,
                        verbose_name='Description',
                    ),
                ),
                (
                    'list4_values',
                    models.CharField(
                        blank=True,
                        help_text='Command template pick list 4 comma-separated values.',
                        max_length=100,
                        verbose_name='Values',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Command Template',
                'verbose_name_plural': 'Command Templates',
                'ordering': ['name', 'os'],
                'unique_together': {('name', 'os')},
            },
        ),
        migrations.AddField(
            model_name='switch',
            name='command_templates',
            field=models.ManyToManyField(
                blank=True,
                help_text='These are the command templates assigned. Users in a group this device belongs to can run these command templates.',
                related_name='command_templates',
                to='switches.CommandTemplate',
                verbose_name='Assigned Command Templates',
            ),
        ),
    ]
