# Generated by Django 3.2.7 on 2021-09-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('switches', '0026_auto_20210928_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='connector_type',
            field=models.PositiveSmallIntegerField(
                choices=[[0, 'SNMP'], [98, 'Commands Only'], [99, 'Napalm'], [100, 'Test Dummy']],
                default=0,
                help_text='How we connect to this device.',
                verbose_name='Connector Type',
            ),
        ),
    ]
