# Generated by Django 3.2.8 on 2021-10-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('switches', '0031_alter_log_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchgroup',
            name='allow_all_vlans',
            field=models.BooleanField(
                default=False, help_text='If set, allow access to all vlans.', verbose_name='Allow All Vlans'
            ),
        ),
    ]
