# Generated by Django 4.2.2 on 2023-06-09 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("switches", "0037_delete_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="switch",
            name="snmp_oid",
        ),
    ]
