# Generated by Django 5.0.6 on 2024-06-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0046_alter_log_action'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='switch',
            unique_together=set(),
        ),
    ]
