# Generated by Django 5.0.6 on 2024-07-08 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0049_switch_access_count_switch_change_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='command_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times a command was run on this device.'),
        ),
        migrations.AddField(
            model_name='switch',
            name='last_command_time',
            field=models.DateTimeField(
                default=datetime.datetime(2000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc),
                help_text='Most recent time a command was run on this device.',
            ),
        ),
    ]
