# Generated by Django 5.0.7 on 2024-08-05 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0051_alter_snmpprofile_udp_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netmikoprofile',
            name='tcp_port',
            field=models.PositiveIntegerField(
                default=22,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(65535),
                ],
                verbose_name='Tcp port',
            ),
        ),
    ]
