# Generated by Django 5.1.1 on 2024-10-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0054_alter_netmikoprofile_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snmpprofile',
            name='auth_protocol',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'none'),
                    (1, 'MD5'),
                    (2, 'SHA'),
                    (3, 'SHA-224'),
                    (4, 'SHA-256'),
                    (5, 'SHA-385'),
                    (6, 'SHA-512'),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name='snmpprofile',
            name='priv_protocol',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'none'),
                    (1, 'DES'),
                    (3, 'AES'),
                    (4, 'AES-192'),
                    (5, 'AES-256'),
                    (6, 'AES-192C'),
                    (7, 'AES-256C'),
                ],
                default=3,
            ),
        ),
    ]
