# Generated by Django 5.1.7 on 2025-04-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0056_snmpprofile_read_only_alter_switch_read_only_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='indent_level',
        ),
        migrations.AddField(
            model_name='switch',
            name='primary_ip6',
            field=models.CharField(
                blank=True,
                help_text='IPv6 address or hostname, can be duplicate as long as device name is unique.',
                max_length=64,
                null=True,
                verbose_name='Management IPv6',
            ),
        ),
    ]
