# Generated by Django 5.2.11 on 2026-03-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0062_alter_switch_connector_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='driver_info',
            field=models.TextField(blank=True, help_text='JSON data provided by the driver.', verbose_name='JSON Info'),
        ),
    ]
