# Generated by Django 5.2.11 on 2026-03-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0064_alter_switch_connector_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='connector_type',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'SNMP'),
                    (1, 'Aruba AOS-CX'),
                    (6, 'Aruba AOS-S REST'),
                    (3, 'Arista eAPI'),
                    (98, 'Commands Only'),
                    (5, 'HPE Comware REST'),
                    (2, 'Junos (PyEZ)'),
                    (99, 'Napalm'),
                    (100, 'Test Dummy'),
                ],
                default=0,
                help_text='How we connect to this device.',
                verbose_name='Connector Type',
            ),
        ),
    ]
