# Generated by Django 6.0.7 on 2026-07-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0067_alter_log_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='read_hardware_details',
            field=models.BooleanField(
                default=True,
                help_text='If set, read hardware details from device.',
                verbose_name='Read Hardware Details',
            ),
        ),
        migrations.AddField(
            model_name='switchgroup',
            name='read_hardware_details',
            field=models.BooleanField(
                default=True,
                help_text='If set, allow reading hardware details from devices in this group.',
                verbose_name='Read Hardware Details',
            ),
        ),
        migrations.AlterField(
            model_name='switchgroup',
            name='allow_all_vlans',
            field=models.BooleanField(
                default=False,
                help_text='If set, allow access to all vlans on devices in this group.',
                verbose_name='Allow All Vlans',
            ),
        ),
        migrations.AlterField(
            model_name='switchgroup',
            name='allow_poe_toggle',
            field=models.BooleanField(
                default=False,
                help_text='If set, allow PoE toggle on all interfaces on devices in this group.',
                verbose_name='Poe Toggle All',
            ),
        ),
        migrations.AlterField(
            model_name='switchgroup',
            name='bulk_edit',
            field=models.BooleanField(
                default=True,
                help_text='If Bulk Edit is set, we can edit multiple interfaces at once on devices in this group.',
                verbose_name='Bulk-editing of interfaces',
            ),
        ),
        migrations.AlterField(
            model_name='switchgroup',
            name='edit_if_descr',
            field=models.BooleanField(
                default=True,
                help_text='If set, allow interface descriptions to be edited on devices in this group.',
                verbose_name='Edit Port Description',
            ),
        ),
        migrations.AlterField(
            model_name='switchgroup',
            name='read_only',
            field=models.BooleanField(
                default=False,
                help_text='If checked, devices in this group are read-only for all users.',
                verbose_name='Read-Only access',
            ),
        ),
    ]
